### ISSUE TITLE
Reorganise pre-commit-config

### ISSUE THREAD

**Issue by MarcoGorelli** [MarcoGorelli/pyladies-sprint-March-2021#21]
Currently, it's structured quite randomly.

Let's instead have:
- third-party hooks
- local hooks

, both sorted alphabetically

**Comment by mgmanzella** [comment]
ill take this one

**Comment by kynan** [comment]
I suggest start with the 3rd party hooks in alpha order and then the local hooks in alpha order.

For local hooks you could also make all id names consistently use `dash-separated-lower-case`.
